<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (c) 2012 NVIDIA Corporation.  All Rights Reserved.

     NVIDIA Corporation and its licensors retain all intellectual property and
     proprietary rights in and to this software and related documentation.  Any
     use, reproduction, disclosure or distribution of this software and related
     documentation without an express license agreement from NVIDIA Corporation
     is strictly prohibited.
 */
-->
<!DOCTYPE AudioConfigs [
  <!ELEMENT AudioConfigs (alsa_device)>
  <!ELEMENT alsa_device (pcm_config, playback, capture, voice-call)>
  <!ELEMENT playback (pcm_config, device, path)>
  <!ELEMENT capture (pcm_config, device, path)>
  <!ELEMENT voice-call (pcm_config, device, path)>
  <!ELEMENT device (path)>
  <!ELEMENT path (ctl)>
  <!ATTLIST alsa_device name (music|voice|aux|voice-call|bt-voice-call|compress_offload) #REQUIRED>
  <!ATTLIST alsa_device card_id CDATA #REQUIRED>
  <!ATTLIST alsa_device card_name CDATA #REQUIRED>
  <!ATTLIST alsa_device device_id CDATA #REQUIRED>
  <!ELEMENT pcm_config EMPTY>
  <!ATTLIST pcm_config rate (8000|11025|16000|22050|32000|44100|48000|64000|88200|96000|176400|192000) #IMPLIED>
  <!ATTLIST pcm_config channels (1|2|3|4|5|6|7|8) #IMPLIED>
  <!ATTLIST pcm_config bps (16|32) #IMPLIED>
  <!ATTLIST pcm_config period_size CDATA #IMPLIED>
  <!ATTLIST pcm_config period_count CDATA #IMPLIED>
  <!ATTLIST pcm_config start_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config stop_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config silence_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config avail_min CDATA #IMPLIED>
  <!ATTLIST device name (speaker|headphone|earpiece|bt-sco|aux|builtin-mic|headset-mic|bt-sco-mic|voice-call|bt-voice-call|compress_offload) #REQUIRED>
  <!ATTLIST path name CDATA #IMPLIED>
  <!ELEMENT param EMPTY>
  <!ATTLIST param name CDATA #REQUIRED>
  <!ATTLIST param val CDATA #REQUIRED>
  <!ELEMENT ctl EMPTY>
  <!ATTLIST ctl name CDATA #REQUIRED>
  <!ATTLIST ctl val CDATA #REQUIRED>
]>
<!--
     This file is used to declare various board specific audio configs
-->

<AudioConfigs>

  <alsa_device name="music"
               card_id="-1"
               card_name="tegra-snd-t210ref-mobile-rt5639"
               device_id="0">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="512"
            period_count="4"
            start_threshold="2047"
            stop_threshold="2048"
            silence_threshold="0"
            avail_min="1"/>
    <param name="ulp" val="0"/>
    <param name="compress_offload" val="0"/>
    <param name="ulp formats" val="mp3 aac"/>
    <param name="ulp rates" val="48000 44100"/>
    <param name="nvoice" val="1"/>
    <param name="HW Rates" val="48000 44100"/>
    <param name="flags" val="AUDIO_OUTPUT_FLAG_PRIMARY"/>
    <param name="HDMI HW Latency" val="50"/>

    <path>
      <!--playback paths-->
      <ctl name="x Speaker Playback Volume" val="0x20"/>
      <ctl name="x HP Playback Volume" val="0x1e"/>
      <ctl name="x Headphone Jack Switch" val="0"/>
      <ctl name="x Int Spk Switch" val="0"/>
      <ctl name="x Int Mic Switch" val="0"/>
      <ctl name="x Mic Jack SwitcH" val="0"/>
      <ctl name="I2S1 Mux" val="MIXER1-1"/>
      <ctl name="MIXER1-1 Mux" val="ADMAIF1"/>
      <ctl name="Adder1 RX1" val="1"/>
      <ctl name="Mixer Enable" val="1"/>
      <ctl name="ADMAIF1 Mux" val="I2S1"/>
    </path>

    <playback>
      <path name="off">
        <ctl name="x Int Spk Switch" val="0"/>
      </path>
      <device name="headphone">
        <path name="on">
          <ctl name="x Headphone Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="x Headphone Jack Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="x SPK MIXR DAC R1 Switch" val="1"/>
          <ctl name="x SPK MIXR DAC R1 Switch" val="0" mode="AUDIO_MODE_IN_CALL" srate="16000"/>
          <ctl name="x SPK MIXR DAC R1 Switch" val="0" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="x Int Spk Switch" val="1"/>
          <ctl name="x Speaker Playback Volume" val="0x20"/>
        </path>
        <path name="off">
          <ctl name="x SPK MIXR DAC R1 Switch" val="1"/>
          <ctl name="x Int Spk Switch" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
          <ctl name="x SPK MIXR DAC R1 Switch" val="0"/>
          <ctl name="x Int Spk Switch" val="1"/>
          <ctl name="x Speaker Playback Volume" val="0x11"/>
        </path>
        <path name="off">
          <ctl name="x SPK MIXR DAC R1 Switch" val="1"/>
        </path>
      </device>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>

      <device name="builtin-mic">
        <path name="on">
          <ctl name="x Stereo ADC L2 Mux" val="DMIC1"/>
          <ctl name="x Stereo ADC R2 Mux" val="DMIC1"/>
          <ctl name="x Stereo ADC MIXL ADC1 Switch" val="0"/>
          <ctl name="x Stereo ADC MIXR ADC1 Switch" val="0"/>
          <ctl name="x Stereo ADC MIXL ADC2 Switch" val="1"/>
          <ctl name="x Stereo ADC MIXR ADC2 Switch" val="1"/>
          <ctl name="x DMIC Switch" val="DMIC1"/>
          <ctl name="x ADC Boost Gain" val="2"/>
          <ctl name="x Int Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="x Stereo ADC MIXL ADC2 Switch" val="0"/>
          <ctl name="x Stereo ADC MIXR ADC2 Switch" val="0"/>
          <ctl name="x ADC Boost Gain" val="0"/>
          <ctl name="x Int Mic Switch" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="x ADC Capture Switch" val="1"/>
          <ctl name="x RECMIXL BST1 Switch" val="0"/>
          <ctl name="x RECMIXR BST1 Switch" val="0"/>
          <ctl name="x RECMIXL BST2 Switch" val="1"/>
          <ctl name="x RECMIXR BST2 Switch" val="1"/>
          <ctl name="x Stereo ADC L1 Mux" val="ADC"/>
          <ctl name="x Stereo ADC R1 Mux" val="ADC"/>
          <ctl name="x Stereo ADC MIXL ADC1 Switch" val="1"/>
          <ctl name="x Stereo ADC MIXR ADC1 Switch" val="1"/>
          <ctl name="x Stereo ADC MIXL ADC2 Switch" val="0"/>
          <ctl name="x Stereo ADC MIXR ADC2 Switch" val="0"/>
          <ctl name="x IN2 Mode Control" val="Single ended"/>
          <ctl name="x IN2 Boost" val="1"/>
          <ctl name="x Mic Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="x RECMIXL BST2 Switch" val="0"/>
          <ctl name="x RECMIXR BST2 Switch" val="0"/>
          <ctl name="x Stereo ADC MIXL ADC1 Switch" val="0"/>
          <ctl name="x Stereo ADC MIXR ADC1 Switch" val="0"/>
          <ctl name="x Mic Jack Switch" val="0"/>
        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name="music"
               card_id="-1"
               card_name="tegra-snd-t210ref-mobile-es755"
               device_id="0">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="512"
            period_count="4"
            start_threshold="2047"
            stop_threshold="2048"
            silence_threshold="0"
            avail_min="1"/>
    <param name="ulp" val="0"/>
    <param name="compress_offload" val="0"/>
    <param name="ulp formats" val="mp3 aac"/>
    <param name="ulp rates" val="48000 44100"/>
    <param name="nvoice" val="0"/>
    <param name="HW Rates" val="48000 44100"/>
    <param name="flags" val="AUDIO_OUTPUT_FLAG_PRIMARY"/>
    <param name="HDMI HW Latency" val="50"/>

    <path>
      <!--Codec paths-->
      <!--AHUB route-->
      <ctl name="ADMAIF1 Mux" val="I2S1"/>
      <ctl name="I2S1 Mux" val="MIXER1-1"/>
      <ctl name="MIXER1-1 Mux" val="ADMAIF1"/>
      <ctl name="Adder1 RX1" val="1"/>
      <ctl name="Mixer Enable" val="1"/>
    </path>

    <playback>
      <device name="headphone">
        <path name="on">
          <ctl name="PT_VP Algorithm" val="On" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP AEC" val="On" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP Primary MUX" val="PDMI0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.0 MUX" val="VP CSOUT1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP Secondary MUX" val="PDMI1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.1 MUX" val="VP FEOUT1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN1 MUX" val="PCM0.0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.0 MUX" val="Pass AUDOUT1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN2 MUX" val="PCM0.1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.1 MUX" val="Pass AUDOUT2" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="HPR MIXER DAC0R" val="1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="HPL MIXER DAC0L" val="1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="HP Gain" val="15" mode="AUDIO_MODE_NORMAL"/>

          <ctl name="PT_VP Algorithm" val="On" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP AEC" val="On" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP Primary MUX" val="PDMI0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.0 MUX" val="VP CSOUT1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP Secondary MUX" val="PDMI1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.1 MUX" val="VP FEOUT1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN1 MUX" val="PCM0.0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.0 MUX" val="Pass AUDOUT1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN2 MUX" val="PCM0.1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.1 MUX" val="Pass AUDOUT2" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="HPR MIXER DAC0R" val="1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="HPL MIXER DAC0L" val="1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="HP Gain" val="15" mode="AUDIO_MODE_RINGTONE"/>

          <ctl name="VP Algorithm" val="On" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="VP FEIN MUX" val="PCM0.0" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="VP FEIN2 MUX" val="PCM0.1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC0.0 MUX" val="VP FEOUT1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC0.1 MUX" val="VP FEOUT2" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="HPR MIXER DAC0R" val="1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="HPL MIXER DAC0L" val="1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="HP Gain" val="15" mode="AUDIO_MODE_IN_COMMUNICATION"/>

          <ctl name="Algo Preset 1" val="918" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Algo Preset 1" val="116" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Algo Preset 1" val="116" mode="AUDIO_MODE_IN_COMMUNICATION"/>

          <ctl name="Algo Preset 1" val="942" mode="AUDIO_MODE_IN_VOICERECOGNITION"/>
        </path>
        <path name="off">
          <ctl name="PT_VP Algorithm" val="Off" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP AEC" val="Off" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP Primary MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.0 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP Secondary MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.1 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN1 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.0 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN2 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.1 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="HPR MIXER DAC0R" val="0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="HPL MIXER DAC0L" val="0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="HP Gain" val="0" mode="AUDIO_MODE_NORMAL"/>

          <ctl name="PT_VP Algorithm" val="Off" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP AEC" val="Off" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP Primary MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.0 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP Secondary MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.1 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN1 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.0 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN2 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.1 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="HPR MIXER DAC0R" val="0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="HPL MIXER DAC0L" val="0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="HP Gain" val="0" mode="AUDIO_MODE_RINGTONE"/>

          <ctl name="VP Algorithm" val="Off" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="VP FEIN MUX" val="None" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="VP FEIN2 MUX" val="None" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC0.0 MUX" val="None" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC0.1 MUX" val="None" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="HPR MIXER DAC0R" val="0" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="HPL MIXER DAC0L" val="0" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="HP Gain" val="0" mode="AUDIO_MODE_IN_COMMUNICATION"/>

          <ctl name="Algo Preset 1" val="918" mode="AUDIO_MODE_IN_VOICERECOGNITION"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="PT_VP Algorithm" val="On" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP AEC" val="On" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP Primary MUX" val="PDMI0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.0 MUX" val="VP CSOUT1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP Secondary MUX" val="PDMI1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.1 MUX" val="VP FEOUT1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN1 MUX" val="PCM0.0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.0 MUX" val="Pass AUDOUT1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN2 MUX" val="PCM0.1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.1 MUX" val="Pass AUDOUT2" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="SPKRR MIXER DAC0R" val="1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="SPKRL MIXER DAC0L" val="1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="SPKR Gain" val="26" mode="AUDIO_MODE_NORMAL"/>

          <ctl name="PT_VP Algorithm" val="On" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP AEC" val="On" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP Primary MUX" val="PDMI0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.0 MUX" val="VP CSOUT1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP Secondary MUX" val="PDMI1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.1 MUX" val="VP FEOUT1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN1 MUX" val="PCM0.0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.0 MUX" val="Pass AUDOUT1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN2 MUX" val="PCM0.1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.1 MUX" val="Pass AUDOUT2" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="SPKRR MIXER DAC0R" val="1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="SPKRL MIXER DAC0L" val="1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="SPKR Gain" val="26" mode="AUDIO_MODE_RINGTONE"/>

          <ctl name="VP Algorithm" val="On" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="VP FEIN MUX" val="PCM0.0" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="VP FEIN2 MUX" val="PCM0.1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC0.0 MUX" val="VP FEOUT1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC0.1 MUX" val="VP FEOUT2" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="SPKRR MIXER DAC0R" val="1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="SPKRL MIXER DAC0L" val="1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="SPKR Gain" val="26" mode="AUDIO_MODE_IN_COMMUNICATION"/>

          <ctl name="Algo Preset 1" val="918" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Algo Preset 1" val="116" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Algo Preset 1" val="116" mode="AUDIO_MODE_IN_COMMUNICATION"/>

          <ctl name="Algo Preset 1" val="942" mode="AUDIO_MODE_IN_VOICERECOGNITION"/>
          <ctl name="Int Spk Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="PT_VP Algorithm" val="Off" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP AEC" val="Off" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP Primary MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.0 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP Secondary MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.1 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN1 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.0 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN2 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.1 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="SPKRR MIXER DAC0R" val="0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="SPKRL MIXER DAC0L" val="0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="SPKR Gain" val="0" mode="AUDIO_MODE_NORMAL"/>

          <ctl name="PT_VP Algorithm" val="Off" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP AEC" val="Off" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP Primary MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.0 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP Secondary MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.1 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN1 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.0 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN2 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.1 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="SPKRR MIXER DAC0R" val="0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="SPKRL MIXER DAC0L" val="0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="SPKR Gain" val="0" mode="AUDIO_MODE_RINGTONE"/>

          <ctl name="VP Algorithm" val="Off" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="VP FEIN MUX" val="None" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="VP FEIN2 MUX" val="None" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC0.0 MUX" val="None" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC0.1 MUX" val="None" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="SPKRR MIXER DAC0R" val="0" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="SPKRL MIXER DAC0L" val="0" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="SPKR Gain" val="0" mode="AUDIO_MODE_IN_COMMUNICATION"/>

          <ctl name="Algo Preset 1" val="918" mode="AUDIO_MODE_IN_VOICERECOGNITION"/>
          <ctl name="Int Spk Switch" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
          <ctl name="PT_VP Algorithm" val="On" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP AEC" val="On" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP Primary MUX" val="PDMI0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.0 MUX" val="VP CSOUT1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP Secondary MUX" val="PDMI1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.1 MUX" val="VP FEOUT1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN1 MUX" val="PCM0.0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.0 MUX" val="Pass AUDOUT1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN2 MUX" val="PCM0.1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.1 MUX" val="Pass AUDOUT2" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="SPKRR MIXER DAC0R" val="1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="SPKRL MIXER DAC0L" val="1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="SPKR Gain" val="20" mode="AUDIO_MODE_NORMAL"/>

          <ctl name="PT_VP Algorithm" val="On" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP AEC" val="On" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP Primary MUX" val="PDMI0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.0 MUX" val="VP CSOUT1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP Secondary MUX" val="PDMI1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.1 MUX" val="VP FEOUT1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN1 MUX" val="PCM0.0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.0 MUX" val="Pass AUDOUT1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN2 MUX" val="PCM0.1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.1 MUX" val="Pass AUDOUT2" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="SPKRR MIXER DAC0R" val="1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="SPKRL MIXER DAC0L" val="1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="SPKR Gain" val="20" mode="AUDIO_MODE_RINGTONE"/>

          <ctl name="VP Algorithm" val="On" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="VP FEIN MUX" val="PCM0.0" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="VP FEIN2 MUX" val="PCM0.1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC0.0 MUX" val="VP FEOUT1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC0.1 MUX" val="VP FEOUT2" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="SPKRR MIXER DAC0R" val="1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="SPKRL MIXER DAC0L" val="1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="SPKR Gain" val="20" mode="AUDIO_MODE_IN_COMMUNICATION"/>

          <ctl name="Algo Preset 1" val="918" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Algo Preset 1" val="116" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Algo Preset 1" val="116" mode="AUDIO_MODE_IN_COMMUNICATION"/>

          <ctl name="Algo Preset 1" val="942" mode="AUDIO_MODE_IN_VOICERECOGNITION"/>
          <ctl name="Int Spk Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="PT_VP Algorithm" val="Off" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP AEC" val="Off" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP Primary MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.0 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP Secondary MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.1 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN1 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.0 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN2 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.1 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="SPKRR MIXER DAC0R" val="0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="SPKRL MIXER DAC0L" val="0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="SPKR Gain" val="0" mode="AUDIO_MODE_NORMAL"/>

          <ctl name="PT_VP Algorithm" val="Off" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP AEC" val="Off" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP Primary MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.0 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP Secondary MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.1 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN1 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.0 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN2 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.1 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="SPKRR MIXER DAC0R" val="0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="SPKRL MIXER DAC0L" val="0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="SPKR Gain" val="0" mode="AUDIO_MODE_RINGTONE"/>

          <ctl name="VP Algorithm" val="Off" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="VP FEIN MUX" val="None" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="VP FEIN2 MUX" val="None" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC0.0 MUX" val="None" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC0.1 MUX" val="None" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="SPKRR MIXER DAC0R" val="0" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="SPKRL MIXER DAC0L" val="0" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="SPKR Gain" val="0" mode="AUDIO_MODE_IN_COMMUNICATION"/>

          <ctl name="Algo Preset 1" val="918" mode="AUDIO_MODE_IN_VOICERECOGNITION"/>
          <ctl name="Int Spk Switch" val="0"/>
        </path>
      </device>
      <device name="headset">
        <path name="on">
          <ctl name="PT_VP Algorithm" val="On" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP AEC" val="On" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP Primary MUX" val="ADC0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.0 MUX" val="VP CSOUT1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.1 MUX" val="VP FEOUT1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN1 MUX" val="PCM0.0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.0 MUX" val="Pass AUDOUT1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN2 MUX" val="PCM0.1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.1 MUX" val="Pass AUDOUT2" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="HPR MIXER DAC0R" val="1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="HPL MIXER DAC0L" val="1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="HP Gain" val="15" mode="AUDIO_MODE_NORMAL"/>

          <ctl name="PT_VP Algorithm" val="On" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP AEC" val="On" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP Primary MUX" val="ADC0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.0 MUX" val="VP CSOUT1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.1 MUX" val="VP FEOUT1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN1 MUX" val="PCM0.0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.0 MUX" val="Pass AUDOUT1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN2 MUX" val="PCM0.1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.1 MUX" val="Pass AUDOUT2" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="HPR MIXER DAC0R" val="1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="HPL MIXER DAC0L" val="1" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="HP Gain" val="15" mode="AUDIO_MODE_RINGTONE"/>

          <ctl name="VP Algorithm" val="On" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="VP FEIN MUX" val="PCM0.0" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="VP FEIN2 MUX" val="PCM0.1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC0.0 MUX" val="VP FEOUT1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC0.1 MUX" val="VP FEOUT2" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="HPR MIXER DAC0R" val="1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="HPL MIXER DAC0L" val="1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="HP Gain" val="15" mode="AUDIO_MODE_IN_COMMUNICATION"/>

          <ctl name="Algo Preset 1" val="552"/>
        </path>
        <path name="off">
          <ctl name="PT_VP Algorithm" val="Off" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP AEC" val="Off" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="VP Primary MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.0 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="PCM0.1 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN1 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.0 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Pass AUDIN2 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC0.1 MUX" val="None" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="HPR MIXER DAC0R" val="0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="HPL MIXER DAC0L" val="0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="HP Gain" val="0" mode="AUDIO_MODE_NORMAL"/>

          <ctl name="PT_VP Algorithm" val="Off" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP AEC" val="Off" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="VP Primary MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.0 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="PCM0.1 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN1 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.0 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="Pass AUDIN2 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="DAC0.1 MUX" val="None" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="HPR MIXER DAC0R" val="0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="HPL MIXER DAC0L" val="0" mode="AUDIO_MODE_RINGTONE"/>
          <ctl name="HP Gain" val="0" mode="AUDIO_MODE_RINGTONE"/>

          <ctl name="VP Algorithm" val="Off" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="VP FEIN MUX" val="None" mode="AUDIO_MODE_IN_COMMUNICATION"/>